[package]
name = "lua_engine"
version = "0.1.2"
edition = "2021"

license-file = "LICENSE"
description = "simple lua engine"
keywords = ["lua", "embedded-scripting"]

[[bin]]
name = "lua-cli"
path = "src/cli.rs"

[dependencies]
lua_engine_macros = { version = "0.1.0", path = "lua_engine_macros" }