[package]
name = "lua_engine"
version = "0.1.0"
edition = "2021"

license-file = "LICENSE"
description = "simple lua engine"
keywords = ["lua", "embedded-scripting"]

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
lua_engine_macros = { path = "lua_engine_macros" }