[package]
name = "lua_engine_macros"
version = "0.1.0"
edition = "2021"

license-file = "../LICENSE"
description = "proc macros for lua engine"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = { version = "2.0" }
